In [2]:
import numpy as np
                            #範圍50~100間,選50位學生各5個成績
students = np.random.randint(50,101,size=(50,5))
students

array([[ 52,  75,  76,  58,  68],
       [ 81,  76,  52,  56,  56],
       [ 77,  50,  74,  59,  56],
       [ 66,  52,  74,  52,  77],
       [ 81,  96,  51,  85,  97],
       [ 91,  86,  69,  82,  95],
       [ 68,  76,  90,  78,  79],
       [ 67,  91,  68,  65,  99],
       [ 64,  78,  81,  51,  91],
       [100,  94,  78,  91, 100],
       [ 94,  54,  58,  51,  56],
       [ 61,  79,  69,  94,  56],
       [ 99,  54,  64,  52,  64],
       [ 85,  62,  64,  60,  76],
       [ 55,  57,  81,  88,  78],
       [ 80,  53,  71,  60,  83],
       [ 58,  90,  88,  88,  91],
       [ 76,  82,  96,  69,  85],
       [ 53,  94,  78,  90,  72],
       [ 67,  52,  97, 100,  79],
       [ 69,  54,  84,  85,  92],
       [ 95,  83,  52,  95,  56],
       [ 81,  62,  63,  99,  88],
       [ 91,  63,  89,  51,  92],
       [ 55,  61,  79,  62,  62],
       [ 96,  85,  83,  96,  68],
       [ 62,  89,  63,  57,  70],
       [ 54,  59,  91,  85,  87],
       [ 60,  59,  74,  55,  94],
       [ 51,  

In [3]:
students[0,0]# Access the first element (0,0) of the array
students[:1,:]# Access the first row of the array
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[ 72,  74,  76,  90,  93],
       [ 60,  75,  99,  52, 100],
       [ 89,  97,  68,  74,  78],
       [ 77,  85,  94,  53,  85],
       [100,  89,  82,  82,  76]])

In [4]:
students[:,0] #第一科所有分數
students[:,-1] #最後一科所有分數

array([ 68,  56,  56,  77,  97,  95,  79,  99,  91, 100,  56,  56,  64,
        76,  78,  83,  91,  85,  72,  79,  92,  56,  88,  92,  62,  68,
        70,  87,  94, 100,  94,  84,  68,  93,  62,  51,  88,  87,  96,
        85,  75,  55,  89,  78,  71,  93, 100,  78,  85,  76])

In [8]:
#axis=1 是按行操作，而 axis=0 则是按列操作。
np.sum(students[:1]) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分 
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

array([73. , 75. , 76. , 69.5, 81. ])